// All renderer imports for browser shell composition stay at this boundary.
export { ContribWiring, WiredPane } from '@/app/contrib/wiring'
export { Button, cn, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger, SearchField } from '@hermes/plugin-sdk'
export { SidebarProvider } from '@/components/ui/sidebar'
export { Codicon } from '@/components/ui/codicon'
export { Tip } from '@/components/ui/tooltip'
export { ActionsMenu, ActionsContextMenu } from '@/components/ui/actions-menu'
export { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'
export { SessionActionsMenu } from '@/app/chat/sidebar/session-actions-menu'
export { ContribRender, ContribBoundary } from '@/contrib/react/boundary'
export { useContributions } from '@/contrib/react/use-contributions'
export { contributedRoutes, ROUTES_AREA, APP_ROUTES, navigateToWorkspacePage } from '@/app/routes'
export { botRosterMeta } from '@/plugins/hermes-bots/routing'
export { displayName } from '@/plugins/hermes-bots/labels'
export { avatarColor, botAppearance, BotFace } from '@/plugins/hermes-bots/avatar'
export { DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger } from '@/components/ui/dropdown-menu'
export { Brain, Power, ShieldLock } from '@/lib/icons'
export { useI18n } from '@/i18n'
export { botSourceStatus } from '@/plugins/hermes-bots/data'
export { GatewayKindGlyph, rosterGatewayOptions } from '@/plugins/hermes-bots/roster-sections'
export type { RosterActivityFilter, RosterKindFilter, RosterRow } from '@/plugins/hermes-bots/types'
export type { useBots } from '@/plugins/hermes-bots/i18n'
export { findGroupOfPane } from '@/components/pane-shell/tree/model'
export { LayoutTreeRoot } from '@/components/pane-shell/tree/renderer'
export { SessionTileCloseConfirm } from '@/app/chat/session-tile'
export { OverlayView } from '@/app/overlays/overlay-view'
export type { TitlebarTool } from '@/app/shell/titlebar-controls'
export type { StatusbarItem } from '@/app/shell/statusbar-controls'

export { BrowserWorkspace } from './browser-workspace'
export { ApprovalToolbarTarget, BackendVersionTarget } from './browser-statusbar'

export { BrowserPageRoutes } from './browser-routes'
