// All renderer imports for browser shell composition stay at this boundary.
export { ContribWiring, WiredPane } from '@/app/contrib/wiring'
export { SidebarProvider } from '@/components/ui/sidebar'
export { Codicon } from '@/components/ui/codicon'
export { Tip } from '@/components/ui/tooltip'
export { ActionsMenu } from '@/components/ui/actions-menu'
export { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'
export { SessionActionsMenu } from '@/app/chat/sidebar/session-actions-menu'
export { ContribRender, ContribBoundary } from '@/contrib/react/boundary'
export { useContributions } from '@/contrib/react/use-contributions'
export { contributedRoutes, ROUTES_AREA, APP_ROUTES, navigateToWorkspacePage } from '@/app/routes'
export { $selectedStoredSessionId, $sessions, $gatewayState, sessionPinId, setSessions } from '@/store/session'
export { $activeConnectionId } from '@/store/connections'
export { useGatewayRequest } from '@/app/gateway/hooks/use-gateway-request'
export { useStatusSnapshot } from '@/app/shell/hooks/use-status-snapshot'
export { GatewayMenuPanel } from '@/app/shell/gateway-menu-panel'
export { $pinnedSessionIds, $sidebarPinsOpen, setSidebarPinsOpen } from '@/store/layout'
export { pinSession, unpinSession } from '@/store/layout'
export { deleteSession, setSessionArchived } from '@/api/sessions'
export { markSessionUnread } from '@/store/session-unread-remote'
export { $activeGatewayProfile, $profileOrder, $profiles, $showAllProfiles, ALL_PROFILES, selectProfile, setProfileOrder, setShowAllProfiles, sortByProfileOrder } from '@/store/profile'
export { $selectedBot } from '@/plugins/hermes-bots/bot-state'
export { $botMeta, $lastRoster } from '@/plugins/hermes-bots/data'
export { botRosterMeta } from '@/plugins/hermes-bots/routing'
export { avatarColor, botAppearance, BotFace } from '@/plugins/hermes-bots/avatar'
export { $layoutTree, removeTreePane, revealTreePane } from '@/components/pane-shell/tree/store'
export { findGroupOfPane } from '@/components/pane-shell/tree/model'
export { LayoutTreeRoot } from '@/components/pane-shell/tree/renderer'
export { SessionTileCloseConfirm } from '@/app/chat/session-tile'
export { OverlayView } from '@/app/overlays/overlay-view'
export type { TitlebarTool } from '@/app/shell/titlebar-controls'

export { BrowserWorkspace } from './browser-workspace'
export { BrowserPanelButton } from './browser-panel-button'
